### PR TITLE
Update mlip-1-legacy to mlip-3

### PR DESCRIPTION
**Pull request by raynol-dsouza**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by raynol-dsouza** [comment]
@conda-forge-admin, please rerender

**Comment by jan-janssen** [comment]
@raynol-dsouza Can you take a look at https://github.com/conda-forge/mlip-feedstock/pull/4 ? At least it seems to work on Linux.

**Comment by raynol-dsouza** [comment]
@jan-janssen Are we creating PRs for the same thing? :D

**Comment by jan-janssen** [comment]
> @jan-janssen Are we creating PRs for the same thing? :D

yes, I had the same feeling

**Comment by raynol-dsouza** [comment]
Took a look at your PR. Yes we are.

**Comment by raynol-dsouza** [comment]
Shall I close this PR then? It seems that there were more changes that needed to be made than Marvin and I anticipated.

**Pull request closed without merging**
